### ISSUE TITLE
Undefined Error?!

### ISSUE THREAD

**Issue by dennis82m** [auth0/auth0-guardian.js#45]
GuardianError

errorCode: undefined

message: undefined

stack: "crossDomainError↵onreadystatechange↵wrapFn↵onInvokeTask↵runTask↵invokeTask↵invokeTask↵globalZoneAwareCallback"

statusCode: undefined

Whats wrong here?
Can'f find the bug.
Safari says it could not load certificate for https://guardian.**.auth0.com/api/start-flow

**Comment by santiagoaguiar** [comment]
Hi there!

The URL for guardian should be `https://<your tenant>.guardian.auth0.com/`. Could you please check that you are using a URL like that one?

If so, could you send us the exact error message that Safari is showing?

Thanks!

**Comment by dennis82m** [comment]
:D now that is embarrassing ... using the correct URL it works

**Comment by santiagoaguiar** [comment]
No problem, glad to hear it's working :).
